#!/usr/bin/env python
# encoding: utf-8

import sys
import traceback
import argh

from sh import ii, sleep, tail

def debug(line):
    print "DEBUG:", line


def handle_commands():
    for line in tail("-f", "irc/irc.freenode.net/#lqdn-stalk/out", n=1, _iter=True):
        date, time, nick, sentence = line.split(" ", 3)
        nick = nick[1:-1]
        print date, time, nick, sentence


def freenode():
    while True:
        try:
            bot = ii(i="irc", s="irc.freenode.net", p=6667, n="DeuxGarage", f="DeuxGarage", _bg=True)
            sleep(5)
            for chan in open("CHANS", "r"):
                print "Va joindre %s" % chan.strip()
                open("irc/irc.freenode.net/in", "w").write("/j %s\n" % chan.strip())
            bot.wait()
        except KeyboardInterrupt:
            print "end"
            return
        except Exception as e:
            traceback.print_exc(file=sys.stdout)
            print e

parser = argh.ArghParser()
parser.add_commands([freenode, handle_commands])

if __name__ == '__main__':
    parser.dispatch()
