#!/usr/bin/env python
# encoding: utf-8

import sys
import traceback
import argh

from sh import ii, sleep, tail

NICK = "DeuxGarage"

def debug(line):
    print "DEBUG:", line


def handle_commands():
    for line in tail("-f", "irc/irc.freenode.net/#lqdn-stalk/out", n=1, _iter=True):
        date, time, nick, sentence = line.split(" ", 3)
        nick = nick[1:-1]
        if nick == NICK:  # I don't want to read myself
            continue

        if sentence.startswith("!bouh"):
            open("irc/irc.freenode.net/#lqdn-stalk/in", "w").write("bah\n")


def join_irc(folder="irc", server="irc.freenode.net", port=6667, nick=NICK, full_name=NICK):
    while True:
        try:
            bot = ii(i=folder, s=server, p=port, n=nick, f=full_name, _bg=True)
            sleep(5)
            for chan in open("CHANS", "r"):
                print "Va joindre %s" % chan.strip()
                open("irc/irc.freenode.net/in", "w").write("/j %s\n" % chan.strip())
            bot.wait()
        except KeyboardInterrupt:
            print "end"
            return
        except Exception as e:
            traceback.print_exc(file=sys.stdout)
            print e

parser = argh.ArghParser()
parser.add_commands([join_irc, handle_commands])

if __name__ == '__main__':
    parser.dispatch()
